::说明：%~dp0 是盘符加路径，即该当前批处理文件.bat文件所在的目录。注=赋值前后不要加空格！！
::当变量中有空格时，必须加双引号括起来！！
::最后测试通过日期：2021-09-25
::复制数据拼接：xcopy /Y %inDir%#A# %outDir%#B#

::变量声明
set inDir=%~dp0
set outDir=%~dp0SetupSourceLatest_WorkHelper\
::创建目录
if not exist %outDir% ( md %outDir%)

::复制文件
xcopy /Y %inDir%Breezee.Framework.BaseUI.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.BaseUI.dll.config %outDir%
xcopy /Y %inDir%Breezee.Framework.DataAccess.INF.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.DataAccess.MySql.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.DataAccess.Oracle.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.DataAccess.PostgreSql.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.DataAccess.SQLite.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.DataAccess.SqlServer.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Doc.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Entity.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Interface.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.BLL.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.DAL.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.DAL.MySql.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.DAL.Oracle.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.DAL.PostgreSql.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.DAL.SQLite.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.DAL.SqlServer.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.Doc.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.Entity.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.IBLL.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.IDAL.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.StartUp.exe %outDir%
xcopy /Y %inDir%Breezee.Framework.Mini.StartUp.exe.config %outDir%
xcopy /Y %inDir%Breezee.Framework.Tool.dll %outDir%
xcopy /Y %inDir%Breezee.Framework.Tool.Inner.dll %outDir%
xcopy /Y %inDir%Breezee.Global.Adapter.BLL.dll %outDir%
xcopy /Y %inDir%Breezee.Global.Adapter.IBLL.dll %outDir%
xcopy /Y %inDir%Breezee.Global.Config.dll %outDir%
xcopy /Y %inDir%Breezee.Global.Context.dll %outDir%
xcopy /Y %inDir%Breezee.Global.Entity.dll %outDir%
xcopy /Y %inDir%Breezee.Global.IOC.dll %outDir%
xcopy /Y %inDir%Breezee.Global.RefOuterDLL.dll %outDir%
xcopy /Y %inDir%Breezee.Global.WinControls.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.BLL.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.DAL.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.DAL.MySql.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.DAL.Oracle.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.DAL.PostgreSql.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.DAL.SQLite.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.DAL.SqlServer.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.Entity.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.IBLL.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.IDAL.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.UI.dll %outDir%
xcopy /Y %inDir%Breezee.WorkHelper.DBTool.UI.dll.config %outDir%
xcopy /Y %inDir%CacheManager.Core.dll %outDir%
xcopy /Y %inDir%CacheManager.Core.xml %outDir%
xcopy /Y %inDir%CacheManager.Memcached.dll %outDir%
xcopy /Y %inDir%CacheManager.Memcached.xml %outDir%
xcopy /Y %inDir%CacheManager.Microsoft.Extensions.Configuration.dll %outDir%
xcopy /Y %inDir%CacheManager.Microsoft.Extensions.Configuration.xml %outDir%
xcopy /Y %inDir%CacheManager.Serialization.fastJSON.dll %outDir%
xcopy /Y %inDir%CacheManager.Serialization.Json.dll %outDir%
xcopy /Y %inDir%CacheManager.Serialization.Json.xml %outDir%
xcopy /Y %inDir%CacheManager.StackExchange.Redis.dll %outDir%
xcopy /Y %inDir%CacheManager.StackExchange.Redis.xml %outDir%
xcopy /Y %inDir%CacheManager.SystemRuntimeCaching.dll %outDir%
xcopy /Y %inDir%CacheManager.SystemRuntimeCaching.xml %outDir%
xcopy /Y %inDir%CacheManager.Web.dll %outDir%
xcopy /Y %inDir%CacheManager.Web.xml %outDir%
xcopy /Y %inDir%Castle.Core.dll %outDir%
xcopy /Y %inDir%Castle.Facilities.Logging.dll %outDir%
xcopy /Y %inDir%Castle.Windsor.dll %outDir%
xcopy /Y %inDir%EntityFramework.dll %outDir%
xcopy /Y %inDir%EntityFramework.SqlServer.dll %outDir%
xcopy /Y %inDir%Enyim.Caching.dll %outDir%
xcopy /Y %inDir%Enyim.Caching.xml %outDir%
xcopy /Y %inDir%fastjson.dll %outDir%
xcopy /Y %inDir%ICSharpCode.SharpZipLib.dll %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Configuration.Abstractions.dll %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Configuration.Abstractions.xml %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Configuration.Binder.dll %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Configuration.Binder.xml %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Configuration.dll %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Configuration.xml %outDir%
xcopy /Y %inDir%Microsoft.Extensions.DependencyInjection.Abstractions.dll %outDir%
xcopy /Y %inDir%Microsoft.Extensions.DependencyInjection.Abstractions.xml %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Primitives.dll %outDir%
xcopy /Y %inDir%Microsoft.Extensions.Primitives.xml %outDir%
xcopy /Y %inDir%Microsoft.ReportViewer.Common.dll %outDir%
xcopy /Y %inDir%Microsoft.ReportViewer.WinForms.dll %outDir%
xcopy /Y %inDir%MySql.Data.dll %outDir%
xcopy /Y %inDir%Newtonsoft.Json.dll %outDir%
xcopy /Y %inDir%Newtonsoft.Json.xml %outDir%
xcopy /Y %inDir%NLog.config %outDir%
xcopy /Y %inDir%NLog.dll %outDir%
xcopy /Y %inDir%Npgsql.dll %outDir%
xcopy /Y %inDir%NPOI.dll %outDir%
xcopy /Y %inDir%NPOI.OOXML.dll %outDir%
xcopy /Y %inDir%NPOI.OpenXml4Net.dll %outDir%
xcopy /Y %inDir%NPOI.OpenXmlFormats.dll %outDir%
xcopy /Y %inDir%Oracle.DataAccess.dll %outDir%
xcopy /Y %inDir%SQLite_DBTool.db %outDir%
xcopy /Y %inDir%SQLite_Mini.db %outDir%
xcopy /Y %inDir%StackExchange.Redis.StrongName.dll %outDir%
xcopy /Y %inDir%StackExchange.Redis.StrongName.xml %outDir%
xcopy /Y %inDir%System.ComponentModel.Primitives.dll %outDir%
xcopy /Y %inDir%System.ComponentModel.TypeConverter.dll %outDir%
xcopy /Y %inDir%System.Data.SQLite.DLL %outDir%
xcopy /Y %inDir%WorkTool.ico %outDir%
xcopy /Y %inDir%zxing.dll %outDir%
xcopy /Y %inDir%Config\IOC.App.Mini.config %outDir%Config\
xcopy /Y %inDir%Config\SQL.App.Mini.config %outDir%Config\
xcopy /Y %inDir%Config\DBTool\IOC.Main.DBTool.config %outDir%Config\DBTool\
xcopy /Y %inDir%Config\DBTool\SQL.Main.DBTool.config %outDir%Config\DBTool\
xcopy /Y %inDir%Config\DBTool\Common\IOC.BLL.DBTool.config %outDir%Config\DBTool\Common\
xcopy /Y %inDir%Config\DBTool\Common\IOC.DAL.DBTool.config %outDir%Config\DBTool\Common\
xcopy /Y %inDir%Config\DBTool\Common\SQL.Common.DBTool.config %outDir%Config\DBTool\Common\
xcopy /Y %inDir%Config\DBTool\MySql\IOC.DAL.MySql.DBTool.config %outDir%Config\DBTool\MySql\
xcopy /Y %inDir%Config\DBTool\MySql\SQL.MySql.DBTool.config %outDir%Config\DBTool\MySql\
xcopy /Y %inDir%Config\DBTool\Oracle\IOC.DAL.Oracle.DBTool.config %outDir%Config\DBTool\Oracle\
xcopy /Y %inDir%Config\DBTool\Oracle\SQL.Oracle.DBTool.config %outDir%Config\DBTool\Oracle\
xcopy /Y %inDir%Config\DBTool\PostgreSql\IOC.DAL.PostgreSql.DBTool.config %outDir%Config\DBTool\PostgreSql\
xcopy /Y %inDir%Config\DBTool\PostgreSql\SQL.PostgreSql.DBTool.config %outDir%Config\DBTool\PostgreSql\
xcopy /Y %inDir%Config\DBTool\SQLite\IOC.DAL.SQLite.DBTool.config %outDir%Config\DBTool\SQLite\
xcopy /Y %inDir%Config\DBTool\SQLite\SQL.SQLite.DBTool.config %outDir%Config\DBTool\SQLite\
xcopy /Y %inDir%Config\DBTool\SqlServer\IOC.DAL.SqlServer.DBTool.config %outDir%Config\DBTool\SqlServer\
xcopy /Y %inDir%Config\DBTool\SqlServer\SQL.SqlServer.DBTool.config %outDir%Config\DBTool\SqlServer\
xcopy /Y %inDir%Config\Mini\IOC.Main.Mini.config %outDir%Config\Mini\
xcopy /Y %inDir%Config\Mini\SQL.Main.Mini.config %outDir%Config\Mini\
xcopy /Y %inDir%Config\Mini\Common\IOC.BLL.Global.Mini.config %outDir%Config\Mini\Common\
xcopy /Y %inDir%Config\Mini\Common\IOC.BLL.Mini.config %outDir%Config\Mini\Common\
xcopy /Y %inDir%Config\Mini\Common\IOC.DAL.Mini.config %outDir%Config\Mini\Common\
xcopy /Y %inDir%Config\Mini\Common\SQL.Common.Mini.config %outDir%Config\Mini\Common\
xcopy /Y %inDir%Config\Mini\Data\DLLList.xml %outDir%Config\Mini\Data\
xcopy /Y %inDir%Config\Mini\Data\KeyValue.xml %outDir%Config\Mini\Data\
xcopy /Y %inDir%Config\Mini\Data\MenuList.xml %outDir%Config\Mini\Data\
xcopy /Y %inDir%Config\Mini\MySql\IOC.DAL.MySql.Mini.config %outDir%Config\Mini\MySql\
xcopy /Y %inDir%Config\Mini\MySql\SQL.MySql.Mini.config %outDir%Config\Mini\MySql\
xcopy /Y %inDir%Config\Mini\Oracle\IOC.DAL.Oracle.Mini.config %outDir%Config\Mini\Oracle\
xcopy /Y %inDir%Config\Mini\Oracle\SQL.Oracle.Mini.config %outDir%Config\Mini\Oracle\
xcopy /Y %inDir%Config\Mini\PostgreSql\IOC.DAL.PostgreSql.Mini.config %outDir%Config\Mini\PostgreSql\
xcopy /Y %inDir%Config\Mini\PostgreSql\SQL.PostgreSql.Mini.config %outDir%Config\Mini\PostgreSql\
xcopy /Y %inDir%Config\Mini\SQLite\IOC.DAL.SQLite.Mini.config %outDir%Config\Mini\SQLite\
xcopy /Y %inDir%Config\Mini\SQLite\SQL.SQLite.Mini.config %outDir%Config\Mini\SQLite\
xcopy /Y %inDir%Config\Mini\SqlServer\IOC.DAL.SqlServer.Mini.config %outDir%Config\Mini\SqlServer\
xcopy /Y %inDir%Config\Mini\SqlServer\SQL.SqlServer.Mini.config %outDir%Config\Mini\SqlServer\
xcopy /Y %inDir%DataTemplate\DBTool\AutoEntity\ColumnConfig.xml %outDir%DataTemplate\DBTool\AutoEntity\
xcopy /Y %inDir%DataTemplate\DBTool\AutoEntity\columnProperty.txt %outDir%DataTemplate\DBTool\AutoEntity\
xcopy /Y %inDir%DataTemplate\DBTool\AutoEntity\columnString.txt %outDir%DataTemplate\DBTool\AutoEntity\
xcopy /Y %inDir%DataTemplate\DBTool\AutoEntity\param.txt %outDir%DataTemplate\DBTool\AutoEntity\
xcopy /Y %inDir%DataTemplate\DBTool\AutoEntity\table.txt %outDir%DataTemplate\DBTool\AutoEntity\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\B.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\D.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\Frm.designer.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\Frm.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\I.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\ID.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\Para.txt %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\AutoFile\模板_生成IBD文件.xlsx %outDir%DataTemplate\DBTool\AutoFile\
xcopy /Y %inDir%DataTemplate\DBTool\DataSQL\模板_生成数据.xlsx %outDir%DataTemplate\DBTool\DataSQL\
xcopy /Y %inDir%DataTemplate\DBTool\StringBuild\模板_合并脚本配置.xml %outDir%DataTemplate\DBTool\StringBuild\
xcopy /Y %inDir%DataTemplate\DBTool\StringBuild\模板_点击拷贝字符.xml %outDir%DataTemplate\DBTool\StringBuild\
xcopy /Y %inDir%DataTemplate\DBTool\TableSQL\1.001_修改表列说明.sql %outDir%DataTemplate\DBTool\TableSQL\
xcopy /Y %inDir%DataTemplate\DBTool\TableSQL\模板_表列备注扩展信息.xlsx %outDir%DataTemplate\DBTool\TableSQL\
xcopy /Y %inDir%DataTemplate\DBTool\TableSQL\模板_表列结构.xlsx %outDir%DataTemplate\DBTool\TableSQL\
xcopy /Y %inDir%Doc\Study\Mariadb常用SQL.sql %outDir%Doc\Study\
xcopy /Y %inDir%Doc\Study\Oracle常用SQL.sql %outDir%Doc\Study\
xcopy /Y %inDir%Doc\Study\PostgreSQL常用SQL.sql %outDir%Doc\Study\
xcopy /Y %inDir%Doc\Study\SQLite常用SQL.sql %outDir%Doc\Study\
xcopy /Y %inDir%Doc\Study\SqlServer常用SQL.sql %outDir%Doc\Study\
xcopy /Y %inDir%Doc\Study\综合SQL比较学习.sql %outDir%Doc\Study\
xcopy /Y %inDir%Help\Html\DBTool\DB\AutoEntity.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\AutoFile.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\DataSqlDBQuery.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\DataSqlExcel.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\DataStringDBQuery.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\DataStringIn.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\DBConnectSet.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\DefaultValueSet.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\MergeScript.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\SqlDBQuery.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\SqlTableColumnRemark.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\SqlTableConstuct.html %outDir%Help\Html\DBTool\DB\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoEntity.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoEntity.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoEntity.003.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.001.02.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.003.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.004.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.005.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.006.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\AutoFile.007.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\CommonMergeScript.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\CommonMergeScript.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\CommonMergeScript.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataSqlDBQuery.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataSqlDBQuery.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataSqlExcelImport.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataSqlExcelImport.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataSqlExcelImport.003.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataSqlExcelImport.004.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataStringDBQuery.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DataStringIn.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DBConnectSet.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DBConnectSet.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\DefaultValue.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\SqlDBQuery.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlDBQuery.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.003.02.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.003.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.004.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.005.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.006.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.007.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlExcelImport.008.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlRemark.001.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlRemark.002.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\DB\Images\TableSqlRemark.jpg %outDir%Help\Html\DBTool\DB\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\CommonCopyString.html %outDir%Help\Html\DBTool\String\
xcopy /Y %inDir%Help\Html\DBTool\String\ExcelColumn2Row.html %outDir%Help\Html\DBTool\String\
xcopy /Y %inDir%Help\Html\DBTool\String\ExcelCopyConn.html %outDir%Help\Html\DBTool\String\
xcopy /Y %inDir%Help\Html\DBTool\String\StringConnChange.html %outDir%Help\Html\DBTool\String\
xcopy /Y %inDir%Help\Html\DBTool\String\StringConnDirectory.html %outDir%Help\Html\DBTool\String\
xcopy /Y %inDir%Help\Html\DBTool\String\StringConnSplit.html %outDir%Help\Html\DBTool\String\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\CommonClickCopy.001.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\CommonClickCopy.002.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\CommonClickCopy.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\ExcelCol2Row.001.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\ExcelCopyConn.001.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\StringDirectoryList.001.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\StringExchangeConn.001.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\DBTool\String\Images\StringSplitConn.001.jpg %outDir%Help\Html\DBTool\String\Images\
xcopy /Y %inDir%Help\Html\Mini\Desktop.html %outDir%Help\Html\Mini\
xcopy /Y %inDir%Help\Html\Mini\DllSet.html %outDir%Help\Html\Mini\
xcopy /Y %inDir%Help\Html\Mini\MenuManage.html %outDir%Help\Html\Mini\
xcopy /Y %inDir%Help\Html\Mini\WorkHelper.html %outDir%Help\Html\Mini\
xcopy /Y %inDir%Help\Html\Mini\Images\Desktop.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\DllSet.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\MenuManage.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.About.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Desktop.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Desktop.002.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Desktop.003.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Env.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Env.002.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Help.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Lock.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Login.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Main.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Menu.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Menu.002.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.ModifyPassword.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Help\Html\Mini\Images\Mini.Support.001.jpg %outDir%Help\Html\Mini\Images\
xcopy /Y %inDir%Image\ShortCut_In.png %outDir%Image\
xcopy /Y %inDir%Image\ShortCut_Out.png %outDir%Image\
xcopy /Y %inDir%Image\保存.ico %outDir%Image\
xcopy /Y %inDir%Image\修改.ico %outDir%Image\
xcopy /Y %inDir%Image\删除.ico %outDir%Image\
xcopy /Y %inDir%Image\导入.ico %outDir%Image\
xcopy /Y %inDir%Image\导出.ico %outDir%Image\
xcopy /Y %inDir%Image\打印.ico %outDir%Image\
xcopy /Y %inDir%Image\新建.ico %outDir%Image\
xcopy /Y %inDir%Image\查询.ico %outDir%Image\
xcopy /Y %inDir%Image\清空.ico %outDir%Image\
xcopy /Y %inDir%Image\确认.ico %outDir%Image\
xcopy /Y %inDir%Image\编辑.ico %outDir%Image\
xcopy /Y %inDir%Image\退出.ico %outDir%Image\
xcopy /Y %inDir%Image\重置.ico %outDir%Image\


::pause

pause
